extends "res://tests/test_core_defense_match.gd"
func shot(m, activation: String):
	m.projectiles.append({"source": 1, "activation_id": activation, "facing": 1.0, "position": m.fighters[2].actor.position + Vector3(-0.45, 0.9, 0), "spawn_tick": -1, "ttl": 96})
func run() -> void:
	var floor = floor_body(); var p = DefenseProfile.new(); p.shield_max = 10; p.shield_drain = 0
	var m = setup_match(p); await settle(m)
	shot(m, "same"); shot(m, "same")
	await tick(m, {2: shield(true)})
	check(m.fighters[2].percent == 0, "breaking hit and duplicate both blocked before damage commit")
	check(m.defense_telemetry(2).state == "break", "exact-cost real projectile breaks shield")
	check(m.projectiles.is_empty(), "shield projectile contacts consumed")
	shot(m, "same")
	await tick(m)
	check(m.fighters[2].percent == 0, "shield contact cannot rehit after break")
	shot(m, "next")
	await tick(m)
	check(m.fighters[2].percent == 8, "new activation damages full break")
	cleanup(m)
	m = setup_match(p); await settle(m)
	shot(m, "b"); shot(m, "a"); shot(m, "b")
	await tick(m, {2: shield(true)})
	check(m.fighters[2].percent == 8, "stable ordered multihit breaks then damages once")
	check(m.defense_telemetry(2).state == "break", "damage interruption cannot cancel break penalty")
	cleanup(m)
	p.shield_max = 100; p.ground_startup_ticks = 1; p.ground_invulnerable_ticks = 1
	m = setup_match(p); await settle(m)
	await tick(m, {2: shield(true, Vector2(0, 1))})
	shot(m, "dodge")
	await tick(m)
	check(m.fighters[2].percent == 0 and m.projectiles.is_empty(), "dodge consumes actual projectile contact")
	shot(m, "dodge")
	await tick(m)
	check(m.fighters[2].percent == 0, "dodged activation cannot rehit recovery")
	cleanup(m); floor.free()
	if not failures: print("PASS: core defense match contacts (%d checks)" % checks)
	quit(1 if failures else 0)
