extends SceneTree
const Specials = preload("res://scripts/core/kits/turbofit_specials.gd")
var failures := 0
func check(ok: bool, label: String) -> void:
	if not ok: failures += 1; printerr("FAIL: ",label)
func _initialize() -> void:
	var kit = Specials.new()
	kit.start("orb-hit",Vector2.DOWN,1); kit.tick(.1)
	kit.tick(0,{"interrupted":true})
	check(kit.snapshot().activation_id == "" and kit.snapshot().phase == "idle", "hit releases episode ownership")
	check(is_equal_approx(kit.snapshot().cooldown,.65), "ordinary interruption must not refund legacy action cooldown")
	check(not kit.start("too-soon",Vector2.ZERO,1), "retained cooldown gates restart")
	kit.tick(1,{"advance":false})
	check(is_equal_approx(kit.snapshot().cooldown,.65), "orphan cooldown also obeys no-advance")
	kit.tick(.65)
	check(kit.start("fresh",Vector2.ZERO,-1), "cooldown completion allows new ownership")
	kit.tick(1.5); kit.tick(.01,{"held":false})
	kit.tick(0,{"interrupted":true,"reason":"reset"})
	check(kit.snapshot().cooldown == 0 and kit.start("after-reset",Vector2.ZERO,1), "reset clears cooldown synchronously")
	kit.cancel()
	kit.start("orb-before-expiry",Vector2.DOWN,1)
	kit.tick(.54)
	var hits: Array = kit.collect(1,Vector3.ZERO,[{"id":8,"position":Vector3(.5,0,0)}])
	kit.tick(.02) # Legacy Orb queries BEFORE decrement, including final crossing step.
	check(hits.size() == 1 and kit.collect(1,Vector3.ZERO,[{"id":9,"position":Vector3(.5,0,0)}]).is_empty(), "orb final interval query precedes expiry decrement")
	kit.cancel(); kit.start("orb-follow",Vector2.DOWN,1)
	check(kit.collect(1,Vector3(20,4,0),[{"id":2,"position":Vector3(20.5,4,0)}]).size() == 1, "orb follows supplied moved origin")
	kit.cancel()
	kit.start("cone-edge",Vector2.ZERO,1); kit.tick(.01,{"held":false})
	var near := Vector3(.399, sqrt(1.0-.399*.399),0)
	var inside := Vector3(.401, sqrt(1.0-.401*.401),0)
	hits = kit.collect(1,Vector3.ZERO,[{"id":8,"position":near},{"id":2,"position":inside},{"id":4,"position":Vector3.RIGHT,"eligible":false}])
	check(hits.size() == 1 and hits[0].victim == 2, "strict .4 cone and eligibility")
	if failures == 0: print("PASS core Turbofit cooldown interruption and contact ordering")
	quit(1 if failures else 0)
