extends "res://tests/test_core_turbo_present_lifecycle.gd"
func run() -> void:
	var v = load("res://scripts/core/presentation/turbofit_presenter.gd").new()
	root.add_child(v)
	var k = load("res://scripts/core/kits/turbofit_specials.gd").new()
	for facing in [-1.0,1.0]:
		v.reset()
		k.cancel()
		k.start("release"+str(facing),Vector2.ZERO,facing)
		k.tick(3.0)
		v.present({"presentation":k.snapshot()},0)
		var starts: int = v.play_count
		k.tick(.01,{"held":false})
		v.present({"presentation":k.snapshot()},0)
		check(v.output.clip == "TwoHandCombo" and is_equal_approx(v.output.seconds,19.0/30),"release restarts immediately at source frame20")
		check(v.play_count == starts+1,"same activation phase restarts playback")
		k.tick(1.0/3)
		v.present({"presentation":k.snapshot()},20)
		check(v.output.clip == "TwoHandCombo" and is_equal_approx(v.output.seconds,29.0/30),"inclusive release frame30 endpoint")
		k.tick(.02)
		v.present({"presentation":k.snapshot()},21)
		check(v.output.clip == "Idle" and is_equal_approx(v.output.blend,.1),"authored .20 return blend uses committed return age")
		var pose := poses(v)
		var out: Dictionary = v.output.duplicate(true)
		for i in 10:
			k.tick(.1,{"hitstop":true})
			v.present({"presentation":k.snapshot(),"hitstop":true},22+i)
		check(poses(v) == pose and v.output == out,"hitstop freezes complete return blend")
		v.present({"presentation":k.snapshot()},40)
		check(poses(v) == pose,"unchanged age freezes blend even advancing host tick")
		k.tick(.2)
		v.present({"presentation":k.snapshot()},41)
		check(v.output.clip == "Idle" and v.output.blend == 1,"return completes without cooldown retiming")
		v.present({"presentation":k.snapshot(),"hit":true,"hit_id":"h"},41)
		check(v.output.clip == "HitReactRight" and v.output.blend == 1,"same tick hit overrides special")
		k.cancel()
		v.present({"presentation":k.snapshot(),"stopped":true},41)
		check(v.output.clip == "Idle" and v.output.identity == "idle" and v.output.blend == 1,"cancel retires special synchronously")
		v.reset()
		check(v.output.is_empty(),"reset clears special state")
	# A newly attached/stopped presenter must not retain a canceled/rest pose.
	k.cancel()
	k.start("late-return",Vector2.ZERO,1)
	k.tick(.01,{"held":false})
	k.tick(.4)
	v.reset()
	v.present({"presentation":k.snapshot(),"stopped":true},0)
	check(v.output.clip == "Idle" and v.output.blend == 1,"synchronous return replacement completes whole blend")
	v.free()
	if not failures: print("PASS: special release frame20 endpoint return blend hitstop cancel reset")
	quit(1 if failures else 0)
