extends "res://tests/test_core_combat_lab.gd"
func run() -> void:
    var lab = load("res://scenes/combat_lab.tscn").instantiate()
    root.add_child(lab)
    lab.set_physics_process(false)
    lab.set_defense_enabled(true)
    lab.set_hitstop_enabled(true)
    for i in 40: await tick(lab)
    key(KEY_O, true)
    await tick(lab)
    check(lab.simulation.defense_telemetry(2).state == "shield" and lab.imported_visuals[1].state.output.clip == "Block", "physical neutral O shields using existing Block")
    key(KEY_F, true)
    var health: float = lab.simulation.defense_telemetry(2).shield_health
    await tick(lab)
    key(KEY_F, false)
    check(lab.simulation.fighters[2].percent == 0 and lab.simulation.defense_telemetry(2).shield_health < health - 9, "real strike spends shield not damage")
    check(lab.simulation.hitstop_telemetry(2).remaining_ticks == 0, "blocked shield contact does not manufacture damage hitstop")
    for i in 250:
        if lab.simulation.defense_telemetry(2).state == "break": break
        await tick(lab)
    check(lab.simulation.defense_telemetry(2).state == "break", "physical held shield drains to full break")
    check(lab.imported_visuals[1].state.output.clip == "Hit", "break uses honest Hit fallback not protective Block")
    check(lab.actors[1].runtime.states.status == "normal", "break fallback never writes fake hitstun")
    key(KEY_O, false)
    lab.reset_lab()
    for i in 40: await tick(lab)
    key(KEY_D, true); key(KEY_E, true)
    await tick(lab)
    check(lab.simulation.defense_telemetry(1).state == "dodge_startup", "physical fresh E+direction starts dodge")
    check(lab.imported_visuals[0].state.output.clip != "Block", "dodge uses locomotion fallback not misleading shield pose")
    key(KEY_D, false); key(KEY_E, false)
    lab.free()
    if failures == 0: print("PASS: defense lab physical shield break and honest fallback presentation")
    quit(1 if failures else 0)
