extends "res://tests/test_core_collision_snapshot.gd"
const Sampler = preload("res://scripts/core/collision/committed_pose_sampler.gd")
const Queries = preload("res://scripts/core/collision/hurtbox_queries.gd")
func run() -> void:
	for id in ["teknium","turbofit"]:
		var path = "res://data/collision/generated/"+id+".tres"
		var bytes = FileAccess.get_file_as_bytes(path)
		var p = load(path)
		var override_path = "res://data/collision/overrides/"+id+"_anatomical_v1.tres"
		# Baseline mode makes excessive core coverage a reproducible RED, not missing-file error.
		var o = load(override_path) if ResourceLoader.exists(override_path) and not "--generated-baseline" in OS.get_cmdline_user_args() else null
		var merged = p.merged_with(o)
		check(merged.errors.is_empty(),id+" shared merger accepts")
		if not merged.errors.is_empty(): continue
		var fit = merged.profile
		for h in fit.hurtboxes:
			if "head" in h.hurtbox_id: check(h.radius <= 12 and h.height <= 34,id+" head excludes hair/empty cap")
			if "hips" in h.hurtbox_id: check(h.radius <= 16 and h.height <= 36,id+" pelvis excludes coat and torso-length cap")
			if id == "turbofit" and "spine" in h.hurtbox_id: check(h.radius <= 17 and h.height <= 36,id+" torso excludes hair/empty cap")
		check(fit.body_radius == p.body_radius and fit.body_height == p.body_height and fit.body_center == p.body_center,id+" native body unchanged")
		check(fit.hurtboxes.size() == p.hurtboxes.size(),id+" stable set")
		for i in fit.hurtboxes.size():
			var h = fit.hurtboxes[i]; var base = p.hurtboxes[i]
			check(h.hurtbox_id == base.hurtbox_id and h.bone_name == base.bone_name,id+" stable bone IDs")
			if not ("head" in h.hurtbox_id or "hips" in h.hurtbox_id or (id == "turbofit" and "spine" in h.hurtbox_id)):
				check(h.radius == base.radius and h.height == base.height and h.local_transform == base.local_transform,id+" untouched limbs")
		if o:
			check(o.source_asset == p.source_asset and o.source_sha256 == p.source_sha256 and o.provenance.generated_profile_sha256 == FileAccess.get_sha256(path),id+" reviewed source and generated identity")
			check(o.manual_override and o.override_fields.is_empty(),id+" explicit nested-only whitelist")
			for h in o.hurtboxes: check(h.manual_override,id+" explicit nested manual flag")
		var packed = load(p.source_asset)
		var model = packed.instantiate(); root.add_child(model)
		var skeleton = model.find_children("*","Skeleton3D",true,false)[0]
		var player = model.find_children("*","AnimationPlayer",true,false)[0]
		var sampler = Sampler.new()
		check(sampler.configure(packed,model.get_path_to(skeleton),model.get_path_to(player)) == OK,id+" real sampler")
		var service = load(BUILDER).new()
		check(service.configure(fit,p.source_asset,p.source_sha256,"anatomical-v1","conservative_affine").is_empty(),id+" shared snapshot")
		var clips = ["Idle","Walk","Punch","Kick"] if id == "teknium" else ["Idle","Walk","MeleeHorizontal","GoalkeeperKick","AirDownKick"]
		for clip in clips:
			for t in [0.0,0.2,player.get_animation(clip).length]:
				for facing in [-1,1]:
					var pose = sampler.sample(clip,t,0)
					var world = Transform3D(Basis(Vector3.UP,facing*PI/2).scaled(Vector3.ONE*p.visual_scale),-p.foot_origin)
					var rev = revision(p,t); rev.clip = clip
					var snap = service.build(id,pose,world,rev)
					check(snap.ok and snap.primitives.size() == p.hurtboxes.size(),id+" full real pose "+clip)
					if not snap.ok: print(snap.diagnostics); continue
					# Deliberate anatomical interior landmarks, NOT all mesh/cloth containment.
					if o:
						for h in o.hurtboxes:
							var primitive = {}
							for c in snap.primitives:
								if c.id == h.hurtbox_id: primitive = c
							for landmark in [Vector3.ZERO,Vector3(5,0,0),Vector3(-5,0,0),Vector3(0,5,0),Vector3(0,-5,0)]:
								var point = world*pose[h.bone_name]*landmark
								check(Queries.sphere_overlap(point,0,primitive),id+" bone-local anatomical interior "+h.hurtbox_id+" "+clip)
		model.free()
		check(bytes == FileAccess.get_file_as_bytes(path),id+" generated bytes unchanged")
	if not failures: print("PASS: two fighter anatomical fit merged snapshots and preserved limbs")
	quit(1 if failures else 0)
