extends "res://tests/test_core_combat_lab.gd"
func pulse(code):
    key(code,true); key(code,false)
func run():
    var lab = load("res://scenes/combat_lab.tscn").instantiate()
    root.add_child(lab)
    lab.set_physics_process(false)
    for i in 40: await tick(lab)
    pulse(KEY_F)
    await tick(lab)
    check(lab.simulation.fighters[2].percent == 8,"lab routes between-sample pulse through native match")
    for i in 40: await tick(lab)
    check(lab.simulation._next_activation == 1,"lab pulse does not replay")
    lab.set_paused(true)
    pulse(KEY_F)
    lab.set_paused(false)
    for i in 40: await tick(lab)
    check(lab.simulation._next_activation == 1,"paused queued-engine pulse cannot ghost on immediate resume")
    pulse(KEY_F)
    lab.reset_lab()
    for i in 40: await tick(lab)
    check(lab.simulation._next_activation == 0,"full lab reset discards pending engine event and captured edge")
    lab.set_p2_input_owner("sparring_easy")
    pulse(KEY_K)
    Input.flush_buffered_events()
    var frame = lab.sources[1].sample(lab.simulation.tick)
    check(frame.pressed.is_empty(),"lab AI-owned P2 ignores human pulse")
    lab.set_p2_input_owner("human")
    pulse(KEY_K)
    Input.flush_buffered_events()
    frame = lab.sources[1].sample(lab.simulation.tick)
    check(frame.pressed.get("attack",false),"same dispatched pulse reaches human P2 control")
    var source = lab.sources[0]
    lab.free()
    check(not Input.joy_connection_changed.is_connected(source._on_joy_connection_changed),"lab shutdown disconnects source")
    if failures == 0: print("PASS core input edge capture lab (7 checks)")
    quit(1 if failures else 0)
