extends "res://tests/test_core_match_strikes.gd"
func run() -> void:
	var m = load("res://scripts/core/match/match_simulation.gd").new()
	var a = Actor.new(); var b = Actor.new(); root.add_child(a); root.add_child(b)
	m.register_actor(1,a); m.register_actor(2,b)
	m.configure_rules(load("res://scripts/core/match/match_rules.gd").new()); m.rematch()
	root.remove_child(b)
	check(not m.fighters[2].enabled, "tree exit disables actor")
	m.rematch()
	check(not m.fighters[2].enabled, "rematch does not revive valid detached actor")
	await tick(m)
	check(not m.fighters[2].enabled, "detached actor is not simulated")
	root.add_child(b)
	check(not m.fighters[2].enabled, "reattach alone does not reactivate actor")
	m.rematch()
	check(m.fighters[2].enabled and b.position == m.rules.stage.spawns[2], "explicit rematch after reattach restores roster")
	a.free(); b.free()
	if not failures: print("PASS: core stocks detached (%d checks)" % checks)
	quit(1 if failures else 0)
