extends "res://tests/test_core_ice_match_shatter.gd"
func run():
	var m = Match.new(); var a = Actor.new(); var b = Actor.new()
	root.add_child(a); root.add_child(b)
	m.register_actor(1,a,-1,"ice_mage"); m.register_actor(2,b,-1,"ice_mage")
	m.reset({1:Vector3(-10,50,0),2:Vector3(0,50,0)})
	await step(m,{2:press(Vector2.ZERO)})
	var budget: float = m.kit_telemetry(2).cast_cooldown
	bolt(m,1,2,"interrupt"); await step(m)
	check(m.fighters[2].frozen,"cast interrupted by actual freeze")
	check(m.kit_telemetry(2).interrupted_cooldown == 0,"reason-aware freeze refunds action cooldown")
	check(is_equal_approx(m.kit_telemetry(2).cast_cooldown,budget-1.0/60),"freeze retains cast budget advances once")
	budget = m.kit_telemetry(2).cast_cooldown
	await step(m)
	check(is_equal_approx(m.kit_telemetry(2).cast_cooldown,budget-1.0/60),"inactive cast budget advances once")
	for i in 20: await step(m)
	check(m.projectile_telemetry().is_empty(),"cancelled delayed cast cannot spawn")
	m.set_enabled(2,false)
	check(m.status_telemetry(2).freeze_remaining == 0 and m.status_telemetry(2).freeze_immunity == 0,"disable clears not thaws")
	m.set_enabled(2,true)
	check(not m.fighters[2].frozen,"reenable no stale freeze")
	bolt(m,1,2,"again"); await step(m)
	check(m.fighters[2].frozen,"reenabled eligible")
	m.configure_actor_kit(2,"turbofit")
	check(not m.fighters[2].frozen and m.status_telemetry(2).freeze_immunity == 0,"kit setup clears status")
	m.set_frozen(2,true)
	m.reset({1:Vector3(-10,50,0),2:Vector3(0,50,0)})
	check(not m.fighters[2].frozen,"reset clears manual seam")
	bolt(m,1,2,"before-reset"); await step(m)
	m.reset({1:Vector3(-10,50,0),2:Vector3(0,50,0)})
	check(m.status_telemetry(2).freeze_remaining == 0 and m.status_telemetry(2).freeze_immunity == 0,"reset clears finite status")
	a.free(); b.free()
	if not failures: print("PASS: ice match status lifecycle (%d checks)" % checks)
	quit(1 if failures else 0)
