extends "res://tests/test_core_match_lifecycle.gd"

func run() -> void:
	await frozen_stun_expiry()
	await frozen_reenable()
	await thaw_remaining_stun()
	await frozen_launch_and_disabled_thaw()
	await frozen_landing_recovery()
	await caught_constraint_cleanup()
	if failures == 0: print("PASS: core status ownership (%d checks)" % checks)
	quit(1 if failures else 0)

func no_normal(a, label: String) -> void:
	for entry in a.runtime.states.trace:
		check(not (entry.layer == "status" and entry.to == "normal"), label + ": no transient normal status")

func caught_constraint_cleanup() -> void:
	for disable in [false, true]:
		var m = Match.new()
		var a = Actor.new()
		var b = Actor.new()
		root.add_child(a); root.add_child(b)
		m.register_actor(1, a); m.register_actor(2, b)
		m.reset({1: Vector3(0, 100, 0), 2: Vector3(1, 100, 0)})
		var grab_input = frame()
		grab_input.pressed.special = true
		await tick(m, {1: grab_input})
		for i in range(11): await tick(m)
		check(m.fighters[2].caught_by == 1 and b.runtime.states.status == "caught", "real grab establishes caught priority")
		await tick(m, {2: frame(true)})
		check(m.fighters[2].buffer.peek("attack").is_empty(), "caught attack still discarded rather than frozen-style queued")
		b.runtime.states.trace.clear()
		if disable: m.set_enabled(2, false)
		else: m.set_frozen(2, true)
		check(b.runtime.states.status == ("disabled" if disable else "frozen"), "caught cleanup retains incoming constraint")
		no_normal(b, "caught constraint cleanup")
		check(m.fighters[2].caught_by == 0 and m.fighters[1].grab == null and a.get_collision_exceptions().is_empty() and b.get_collision_exceptions().is_empty(), "both grab endpoints and collision exceptions released")
		check(m.fighters[2].grab_immune_until == m.tick + 60, "cleanup preserves existing grab immunity only")
		if disable: m.set_enabled(2, true)
		else: m.set_frozen(2, false)
		await tick(m)
		check(m.fighters[2].activation_id.is_empty(), "caught press never replays on release")
		await tick(m, {2: frame(true, 1.0)})
		check(not m.fighters[2].activation_id.is_empty() and b.velocity.x > 0, "released fighter accepts a fresh attack and movement")
		a.free(); b.free()

func frozen_launch_and_disabled_thaw() -> void:
	var m = Match.new()
	var a = Actor.new()
	var b = Actor.new()
	root.add_child(a); root.add_child(b)
	m.register_actor(1, a); m.register_actor(2, b)
	m.reset({1: Vector3(0, 100, 0), 2: Vector3(1, 100, 0)})
	m.set_frozen(1, true)
	a.runtime.states.trace.clear()
	a.apply_combat_launch(Vector3(4, 0, 0), 2)
	check(a.runtime.states.status == "frozen", "direct incoming launch cannot override freeze")
	no_normal(a, "direct frozen launch")
	# A real resolver launch later in the same update must also finish frozen.
	await tick(m, {1: frame(true, 1.0), 2: frame(true, -1.0)})
	check(m.fighters[1].percent > 0 and a.runtime.hitstun_left > 0, "frozen victim still receives real damage and stun, no immunity")
	check(a.runtime.states.status == "frozen" and m.fighters[1].activation_id.is_empty() and a.position.x == 0, "resolved hit leaves freeze authoritative at tick completion")
	no_normal(a, "resolved frozen launch")
	m.set_enabled(1, false)
	var remaining: int = a.runtime.hitstun_left
	m.set_frozen(1, false)
	check(a.runtime.states.status == "disabled", "thaw cannot erase disable")
	await tick(m, {1: frame(true)})
	check(a.runtime.hitstun_left == remaining and m.fighters[1].buffer.peek("attack").is_empty(), "disabled stun clock and input remain paused")
	m.set_frozen(1, true)
	check(a.runtime.states.status == "disabled", "freeze cannot erase disable")
	m.set_enabled(1, true)
	check(a.runtime.states.status == "frozen", "reenable retains incoming freeze over remaining stun")
	m.reset({1: Vector3(0, 100, 0), 2: Vector3(5, 100, 0)})
	check(a.runtime.states.status == "normal" and not m.fighters[1].frozen and a.runtime.hitstun_left == 0, "reset clears all status constraints")
	await tick(m, {1: frame(true, 1.0)})
	check(not m.fighters[1].activation_id.is_empty() and a.position.x > 0, "reset restores real action and movement")
	a.free(); b.free()

func frozen_landing_recovery() -> void:
	var m = Match.new()
	var floor = floor_body()
	var a = Actor.new()
	root.add_child(a)
	m.register_actor(1, a)
	m.reset({1: Vector3(0, 0.25, 0)})
	a.apply_combat_launch(Vector3(0, -5, 0), 12)
	m.set_frozen(1, true)
	while a.runtime.hitstun_left > 0: await tick(m)
	check(a.runtime.grounded and a.runtime.states.status == "frozen", "terrain landing and stun expiry retain freeze")
	# Freeze is not permission to consume deferred landing recovery.
	for i in range(2): await tick(m)
	m.set_frozen(1, false)
	check(a.runtime.states.action == "landing_lock" and not a.can_accept_jump(), "thaw restores deferred landing gate")
	for i in range(a.profile.landing_ticks):
		await tick(m, {1: frame(i == 0)})
		check(m.fighters[1].activation_id.is_empty() and not m.fighters[1].buffer.peek("attack").is_empty(), "attack remains queued through all deferred landing ticks")
	await tick(m)
	check(not m.fighters[1].activation_id.is_empty() and m.fighters[1].buffer.peek("attack").is_empty(), "landing completion accepts queued attack")
	a.free(); floor.free()

func thaw_remaining_stun() -> void:
	var m = Match.new()
	var a = Actor.new()
	root.add_child(a)
	m.register_actor(1, a)
	m.reset({1: Vector3(0, 100, 0)})
	a.apply_combat_launch(Vector3(5, 2, 0), 20)
	m.set_frozen(1, true)
	await tick(m)
	a.runtime.states.trace.clear()
	m.set_frozen(1, false)
	check(a.runtime.hitstun_left == 19 and a.runtime.states.status == "hitstun", "thaw restores remaining stun immediately")
	no_normal(a, "thaw with stun")
	await tick(m, {1: frame(true, 1.0)})
	check(m.fighters[1].activation_id.is_empty() and not m.fighters[1].buffer.peek("attack").is_empty(), "thawed stunned input queues, not accepts")
	for i in range(6): await tick(m)
	check(m.fighters[1].buffer.peek("attack").is_empty() and m.fighters[1].activation_id.is_empty(), "stunned queue expires normally without activation")
	while a.runtime.hitstun_left > 3:
		check(a.runtime.states.status == "hitstun", "no normal window before stun completes")
		await tick(m)
	for i in range(3):
		await tick(m, {1: frame(i == 0)})
		check(m.fighters[1].activation_id.is_empty() and not m.fighters[1].buffer.peek("attack").is_empty(), "fresh near-expiry attack retained through last stun tick")
	check(a.runtime.hitstun_left == 0 and a.runtime.states.status == "normal", "exact remaining clock completes")
	await tick(m, {1: frame(false, 1.0)})
	check(not m.fighters[1].activation_id.is_empty() and m.fighters[1].buffer.peek("attack").is_empty() and a.velocity.x > 0, "first legal post-stun tick accepts attack and movement")
	a.free()

func frozen_reenable() -> void:
	var m = Match.new()
	var a = Actor.new()
	root.add_child(a)
	m.register_actor(1, a)
	m.reset({1: Vector3(0, 100, 0)})
	m.set_frozen(1, true)
	await tick(m, {1: frame(true)})
	check(not m.fighters[1].buffer.peek("attack").is_empty(), "freeze queues attack before disable")
	m.set_enabled(1, false)
	check(a.runtime.states.status == "disabled" and m.fighters[1].buffer.peek("attack").is_empty(), "disable wins and clears queue")
	var at: Vector3 = a.position
	await tick(m, {1: frame(true, 1.0)})
	check(a.position == at and m.fighters[1].buffer.peek("attack").is_empty(), "disabled input ignored and body stopped")
	a.runtime.states.trace.clear()
	m.set_enabled(1, true)
	check(m.fighters[1].frozen and a.runtime.states.status == "frozen", "reenable restores freeze synchronously")
	no_normal(a, "reenable")
	for i in range(3):
		await tick(m, {1: frame(i == 0, 1.0)})
		check(a.position.x == at.x and m.fighters[1].activation_id.is_empty(), "reenabled frozen rejects actual movement and attack")
		check(not m.fighters[1].buffer.peek("attack").is_empty(), "reenabled freeze retains unexpired queue")
	m.set_frozen(1, false)
	await tick(m, {1: frame(false, 1.0)})
	check(not m.fighters[1].activation_id.is_empty() and m.fighters[1].buffer.peek("attack").is_empty() and a.position.x > at.x, "reenable then thaw resumes queued attack and movement")
	a.free()

func frozen_stun_expiry() -> void:
	var m = Match.new()
	var a = Actor.new()
	root.add_child(a)
	m.register_actor(1, a)
	m.reset({1: Vector3(0, 100, 0)})
	a.apply_combat_launch(Vector3(5, 2, 0), 1)
	m.set_frozen(1, true)
	a.runtime.states.trace.clear()
	var x: float = a.position.x
	await tick(m, {1: frame(true, 1.0)})
	check(a.runtime.hitstun_left == 0, "freeze keeps existing hitstun clock advancing")
	check(m.fighters[1].frozen and a.runtime.states.status == "frozen", "stun expiry preserves freeze")
	check(a.position.x == x, "frozen stun blocks horizontal motion")
	no_normal(a, "frozen expiry")
	for i in range(2):
		await tick(m, {1: frame(false, 1.0)})
		check(m.fighters[1].activation_id.is_empty() and not m.fighters[1].buffer.peek("attack").is_empty(), "frozen attack remains queued, never accepted")
		check(a.position.x == x and a.runtime.states.status == "frozen", "freeze gates every movement tick")
	m.set_frozen(1, false)
	check(a.runtime.states.status == "normal", "thaw after expiry resumes normal")
	await tick(m, {1: frame(false, 1.0)})
	check(not m.fighters[1].activation_id.is_empty() and m.fighters[1].buffer.peek("attack").is_empty(), "first legal tick consumes queued attack")
	check(a.position.x > x, "normal movement resumes")
	m.reset({1: Vector3(0, 100, 0)})
	m.set_frozen(1, true)
	for i in range(7):
		var held_attack = frame(i == 0, 1.0)
		held_attack.held.attack = true
		await tick(m, {1: held_attack})
		check(m.fighters[1].activation_id.is_empty() and a.runtime.states.status == "frozen", "long freeze never accepts held attack")
	check(m.fighters[1].buffer.peek("attack").is_empty(), "frozen queue expires at ordinary buffer boundary")
	m.set_frozen(1, false)
	var held_only = frame()
	held_only.held.attack = true
	await tick(m, {1: held_only})
	check(m.fighters[1].activation_id.is_empty(), "expired frozen edge cannot replay on thaw or held input")
	a.free()
