extends "res://tests/test_core_turbo_match_routes.gd"
func run():
	var floor = floor_body(); var m = Match.new(); var a = Actor.new(); var b = Actor.new()
	root.add_child(a); root.add_child(b); m.register_actor(1,a,-1,"turbofit"); m.register_actor(2,b,-1,"turbofit")
	m.reset({1:Vector3(0,.01,0),2:Vector3(1.5,.01,0)})
	for i in 12: await step(m)
	await step(m,{1:press(Vector2.RIGHT,"attack"),2:press(Vector2.LEFT,"attack")})
	for i in 16: await step(m)
	check(m.fighters[1].percent == 14 and m.fighters[2].percent == 14, "duplicate Turbofit trades use single pre-resolution snapshot")
	check(m.fighters[1].kit != m.fighters[2].kit, "per-actor adapter isolation")
	check(m.kit_telemetry(1).has("simulation_tick") and m.kit_telemetry(1).has("presentation"), "committed kit/presentation telemetry exposes local clock")
	m.reset({1:Vector3(0,.01,0),2:Vector3(10,.01,0)})
	for i in 12: await step(m)
	await step(m,{1:press(Vector2.RIGHT,"attack")})
	m.set_frozen(1,true)
	check(not m.kit_telemetry(1).basic.active and m.kit_telemetry(1).action_locked, "freeze interrupts episode but retains cooldown")
	for i in 20: await step(m,{1:press(Vector2.RIGHT,"attack")})
	check(not m.kit_telemetry(1).basic.active, "frozen actor never starts buffered attacks")
	m.set_frozen(1,false)
	m.configure_actor_kit(1,"teknium")
	m.reset({1:Vector3(0,.01,0),2:Vector3(1,.01,0)})
	for i in 12: await step(m)
	await step(m,{1:press(Vector2.ZERO),2:press(Vector2.DOWN,"attack")})
	for i in 11: await step(m)
	check(m.fighters[2].caught_by == 1 and not m.kit_telemetry(2).basic.active, "actual Teknium capture cancels Turbofit windup")
	for i in 20: await step(m,{2:press(Vector2.ZERO)})
	check(m.kit_telemetry(2).special.phase == "idle" and m.fighters[2].buffer.peek("special").is_empty(), "caught input discarded, no charge fallback")
	m.configure_actor_kit(1,"turbofit")
	var rules = load("res://scripts/core/match/match_rules.gd").new(); rules.stock_count = 1
	m.configure_rules(rules); m.rematch()
	await step(m,{1:press(Vector2.RIGHT)})
	check(not m.projectile_telemetry().is_empty(), "pre-KO wave emitted")
	a.position.y = -10; await step(m)
	check(m.result.get("kind","") == "WIN" and m.result.winner_id == 2, "mixed kit lifecycle commits KO and result")
	check(m.projectile_telemetry().is_empty() and not m.kit_telemetry(1).action_locked, "results clear detached ownership and cooldowns")
	var stopped_tick: int = m.tick
	await step(m,{2:press(Vector2.ZERO)})
	check(m.tick == stopped_tick and m.kit_telemetry(2).special.phase == "idle", "results stop kit and world clocks")
	m.rematch(); await step(m)
	check(m.result.is_empty() and m.fighters[1].enabled and m.fighters[1].kit_id == "turbofit", "rematch restores selected kit without stale input")
	check(not m.configure_actor_kit(1,"missing") and m.fighters[1].kit_id == "turbofit", "unknown factory rejects without side effects")
	a.free(); b.free(); floor.free()
	if not failures: print("PASS: turbo match lifecycle (%d checks)" % checks)
	quit(1 if failures else 0)
