extends "res://tests/test_core_combat_lab.gd"
func run() -> void:
    var lab = load("res://scenes/combat_lab.tscn").instantiate()
    root.add_child(lab)
    lab.set_physics_process(false)
    lab.select_fighter(0,"turbofit")
    lab.select_fighter(1,"turbofit")
    for i in range(40): await tick(lab)
    lab.actors[0].position = Vector3(-10,20,0)
    lab.actors[1].position = Vector3(10,20,0)
    key(KEY_D,true)
    key(KEY_G,true)
    await tick(lab)
    key(KEY_D,false)
    key(KEY_G,false)
    var first: Dictionary = lab.simulation.projectile_telemetry()[0]
    check(lab.projectile_visuals.has(first.activation_id), "detached wave rendered from combined committed telemetry")
    check(lab.get_snapshot().projectiles.size() == 1, "wave exposed in browser diagnostics")
    lab.actors[1].position = first.position - Vector3.UP + Vector3(.9,0,0)
    lab.actors[1].runtime.velocity = lab.actors[0].runtime.velocity
    lab.actors[0].position.x = -30
    key(KEY_DOWN,true)
    key(KEY_L,true)
    await tick(lab)
    key(KEY_DOWN,false)
    key(KEY_L,false)
    var shots: Array = lab.simulation.projectile_telemetry()
    check(shots.size() == 1 and shots[0].source == 2, "real physical Orb reflection")
    check(lab.get("orb_visuals") != null and lab.orb_visuals.size() == 1, "attached active Orb debug visual")
    if lab.projectile_visuals.has(first.activation_id):
        var visual: MeshInstance3D = lab.projectile_visuals[first.activation_id]
        check(visual.global_position.is_equal_approx(shots[0].position), "current full world pose")
        check(visual.get_meta("source") == 2 and visual.get_meta("facing") == -1, "current reflected ownership and pose")
        check(visual.material_override.albedo_color.r > visual.material_override.albedo_color.g, "P2 reflected orange")
        check(shots[0].age > first.age and shots[0].distance > first.distance, "finite budgets not renewed")
    lab.set_paused(true)
    lab.simulation.cancel_action(2,"caught fixture")
    lab._sync_visuals()
    if lab.get("orb_visuals") != null: check(lab.orb_visuals.is_empty(), "paused cancellation immediately removes Orb")
    lab.simulation.expire_source(1,"old owner")
    lab._sync_visuals()
    check(lab.projectile_visuals.size() == 1, "old owner cleanup retains reflected Wave")
    lab.simulation.expire_source(2,"current owner")
    lab._sync_visuals()
    check(lab.projectile_visuals.is_empty(), "paused current owner cleanup removes Wave immediately")
    lab.reset_lab()
    if lab.get("orb_visuals") != null: check(lab.orb_visuals.is_empty(), "reset clears all attached effects")
    lab.free()
    if not failures: print("PASS: combined Wave Orb rendering reflected source finite clocks synchronous cleanup")
    quit(1 if failures else 0)
