extends SceneTree
var failures := 0
func check(ok: bool, label: String) -> void:
	if not ok:
		failures += 1
		print("FAIL: ",label)
func _init() -> void: call_deferred("run")
func poses(v) -> Array:
	var a: Array = []
	for b in v.skeleton.get_bone_count(): a.append(v.skeleton.get_bone_pose(b))
	return a
func run() -> void:
	var v = load("res://scripts/core/presentation/ice_mage_presenter.gd").new()
	root.add_child(v)
	v.present({"velocity":Vector3(2,0,0)},0)
	v.present({"velocity":Vector3(2,0,0)},12)
	check(is_equal_approx(v.output.seconds,.2),"locomotion advances only committed clock")
	if failures: v.free(); quit(1); return
	v.present({"velocity":Vector3(5,0,0)},13)
	v.present({"velocity":Vector3(5,0,0)},14)
	check(v.output.blend > 0 and v.output.blend < 1,"fixture enters actual transition blend")
	var frozen := poses(v)
	var out: Dictionary = v.output.duplicate(true)
	for i in 10: v.present({"velocity":Vector3(5,0,0)},14)
	check(poses(v)==frozen and v.output==out,"same tick freezes whole blend not just source")
	v.present({"velocity":Vector3(5,0,0),"hitstop":true},40)
	check(poses(v)==frozen and v.output==out,"hitstop excludes external world tick gap")
	v.present({"velocity":Vector3(5,0,0)},41)
	check(is_equal_approx(v.output.elapsed,2.0/60),"resume only next committed delta")
	var host = load("res://scripts/core/kits/ice_mage_host.gd").new()
	host.start_basic("one",Vector2.RIGHT,false,1)
	host.prepare(false)
	v.present({"presentation":host.snapshot().presentation},42)
	frozen = poses(v)
	var count: int = v.play_count
	v.present({"presentation":host.snapshot().presentation},80)
	check(poses(v)==frozen and v.play_count==count,"unchanged real kit elapsed freezes episode despite world tick")
	host.cancel(true)
	host.start_basic("two",Vector2.RIGHT,false,1)
	v.present({"presentation":host.snapshot().presentation},80)
	check(v.output.seconds==0 and v.play_count==count+1,"new same-clip identity restarts at unchanged tick")
	host.prepare(false)
	v.present({"presentation":host.snapshot().presentation},81)
	host.cancel()
	v.present({"presentation":host.snapshot().presentation,"hitstop":true},81)
	check(v.output.clip=="Idle" and v.output.blend==1,"synchronous cancel completes replacement even stopped")
	var oracle = load("res://scripts/core/presentation/ice_mage_presenter.gd").new()
	root.add_child(oracle)
	oracle.present({},0)
	for b in v.skeleton.get_bone_count(): check(v.skeleton.get_bone_pose(b).is_equal_approx(oracle.skeleton.get_bone_pose(b)),"cancel actually replaces imported skeleton with complete Idle")
	oracle.free()
	v.present({"status":"hitstun","hit_id":"h1"},82)
	v.present({"status":"hitstun","hit_id":"h1"},84)
	count = v.play_count
	v.present({"status":"hitstun","hit_id":"h1","locomotion":"jump_startup","air_jumps_left":0},85)
	check(v.play_count==count and v.output.elapsed>0,"lower priority jump cannot restart hit")
	v.present({"status":"hitstun","hit_id":"h2"},85)
	check(v.play_count==count+1 and v.output.elapsed==0,"new hit episode restarts fallback")
	v.present({"electrocution":{"activation_id":"grab","elapsed":.4}},85)
	v.present({"frozen":true,"electrocution":{"activation_id":"grab","elapsed":.4}},85)
	check(v.output.identity=="frozen" and v.output.blend==1,"freeze synchronously discards relation pose")
	frozen = poses(v)
	v.present({"frozen":true},100)
	check(poses(v)==frozen,"frozen Idle remains still")
	v.reset()
	check(v.output.is_empty(),"explicit reset clears episode")
	v.present({"velocity":Vector3(2,0,0)},0)
	check(v.output.seconds==0 and v.output.blend==1,"reset starts completed replacement pose")
	v.present({"velocity":Vector3(2,0,0)},30)
	v.present({"velocity":Vector3(2,0,0)},0)
	check(v.output.seconds==0,"tick rewind resets clock")
	v.free()
	if not failures: print("PASS: core Ice presentation committed clocks whole blend pause hitstop sync lifecycle")
	quit(1 if failures else 0)
