extends "res://tests/test_core_combat_lab.gd"
# Characterize authoritative policies through physical input and the new view.
func run() -> void:
    var lab = load("res://scenes/combat_lab.tscn").instantiate()
    root.add_child(lab)
    lab.set_physics_process(false)
    for i in range(40): await tick(lab)
    # Bring the real actors within the strict 1.3 origin box using keyboard.
    key(KEY_D, true)
    for i in range(10): await tick(lab)
    key(KEY_D, false)
    for i in range(10): await tick(lab)
    key(KEY_W, true)
    key(KEY_G, true)
    await tick(lab)
    key(KEY_W, false)
    key(KEY_G, false)
    check(lab.simulation.fighters[2].percent == 12.0, "physical recovery in range damages exactly 12")
    check(lab.imported_visuals[1].state.output.clip == "Hit", "real recovery contact presents victim Hit")
    var visual = lab.imported_visuals[0]
    var f: Dictionary = lab.simulation.fighters[1]
    var id: String = f.activation_id
    lab.set_paused(true)
    var frozen: Dictionary = visual.state.output.duplicate(true)
    var before: int = lab.simulation.tick
    for i in range(3): await tick(lab)
    check(lab.simulation.tick == before and visual.state.output == frozen, "pause freezes source clock and physics")
    lab.step_once()
    await tick(lab)
    check(lab.simulation.tick == before + 1 and f.recovery.age == 2, "step advances one recovery tick")
    lab.set_paused(false)
    for i in range(38): await tick(lab)
    check(lab.simulation.fighters[2].percent == 12.0, "same activation never repeats damage")
    check(lab.actors[0].runtime.recovery_spent and not lab.actors[0].runtime.grounded, "cooldown ends while aerial resource remains spent")
    key(KEY_W, true)
    key(KEY_G, true)
    for i in range(8): await tick(lab)
    key(KEY_W, false)
    key(KEY_G, false)
    check(f.activation_id == "" and f.recovery == null, "fresh physical special cannot repeat before terrain")
    for i in range(100):
        await tick(lab)
        if lab.actors[0].runtime.grounded and lab.actors[0].runtime.states.movement_allowed(): break
    check(not lab.actors[0].runtime.recovery_spent, "real descending terrain contact restores resource")
    key(KEY_W, true)
    key(KEY_G, true)
    await tick(lab)
    key(KEY_W, false)
    key(KEY_G, false)
    check(f.recovery != null and f.activation_id != id, "physical recovery accepts again after real terrain landing")
    lab.simulation.cancel_action(1, "test explicit interruption")
    await tick(lab)
    check(visual.state.output.clip != "RaiseWall" and lab.actors[0].runtime.recovery_spent, "cancellation ends pose without refund")
    # Airborne launch after a real keyboard jump, then disable/reset interruption.
    lab.reset_lab()
    for i in range(40): await tick(lab)
    key(KEY_SPACE, true)
    for i in range(12): await tick(lab)
    key(KEY_SPACE, false)
    check(not lab.actors[0].runtime.grounded, "airborne test starts from physical jump")
    key(KEY_W, true)
    key(KEY_G, true)
    await tick(lab)
    key(KEY_W, false)
    key(KEY_G, false)
    check(is_equal_approx(lab.actors[0].velocity.y, 13.5), "physical airborne recovery replaces jump with one impulse")
    await tick(lab)
    check(is_equal_approx(lab.actors[0].velocity.y, 13.5 - 32.0 / 60.0), "gravity resumes without repeat impulse or short hop")
    lab.simulation.set_enabled(1, false)
    await tick(lab)
    check(visual.state.output.clip != "RaiseWall" and f.recovery == null, "disable interrupts episode")
    lab.reset_lab()
    check(not lab.actors[0].runtime.recovery_spent and f.activation_id == "" and visual.state.output.clip != "RaiseWall", "reset clears resources and presentation episode")
    var policy = load("res://scripts/core/presentation/presentation_state.gd").new()
    var pose := {"recovery_id": "r", "recovery_elapsed": .2, "strike_id": "s", "force_id": "f", "action": "block", "locomotion": "rising"}
    check(policy.sample(pose, 1).clip == "RaiseWall", "recovery overrides block, strike, force and locomotion")
    pose.status = "hitstun"
    check(policy.sample(pose, 2).clip == "Hit", "Hit overrides recovery")
    lab.free()
    if failures == 0: print("PASS: recovery lab real contacts, resource gates, airborne impulse, pause/step and interruptions")
    quit(1 if failures else 0)
