extends "res://tests/test_core_recovery_acceptance.gd"
func bolt(m, source: int, target: int, identity: String):
	m._commit_kit_intents([{"kind":"spawn_projectile","projectile_kind":"frost_bolt","source":source,"activation_id":identity,"position":m.fighters[target].actor.position+Vector3(-.5,1,0),"facing":1.0}])
func run():
	for kit in ["teknium","turbofit","ice_mage"]:
		var m = Match.new(); var a = Actor.new(); var b = Actor.new()
		root.add_child(a); root.add_child(b)
		m.register_actor(1,a,-1,"ice_mage"); m.register_actor(2,b,-1,kit)
		m.reset({1:Vector3(-10,50,0),2:Vector3(0,50,0)})
		bolt(m,1,2,"first"); await step(m)
		check(m.fighters[2].frozen and m.fighters[2].percent == 4,"first real contact freezes "+kit)
		bolt(m,1,2,"second"); await step(m)
		check(not m.fighters[2].frozen,"positive damage shatters "+kit)
		check(m.fighters[2].percent == 8 and b.runtime.hitstun_left > 0,"shatter retains damage launch "+kit)
		check(m.status_telemetry(2).freeze_immunity == 1.0,"shatter before same-hit refreeze full immunity "+kit)
		bolt(m,1,2,"third"); await step(m)
		check(not m.fighters[2].frozen and m.fighters[2].percent == 12,"immune bolt still damages "+kit)
		for i in 58: await step(m)
		check(m.status_telemetry(2).freeze_immunity > 0,"immunity just before endpoint "+kit)
		bolt(m,1,2,"endpoint"); await step(m)
		check(m.fighters[2].frozen,"immunity subtracts before exact endpoint contact "+kit)
		a.free(); b.free()
	# Same-frame contacts are atomic in deterministic source/activation order.
	var m = Match.new(); var a = Actor.new(); var b = Actor.new()
	root.add_child(a); root.add_child(b)
	m.register_actor(1,a,-1,"ice_mage"); m.register_actor(2,b,-1,"ice_mage")
	m.reset({1:Vector3(-10,50,0),2:Vector3(0,50,0)})
	bolt(m,1,2,"a"); bolt(m,1,2,"b"); await step(m)
	check(m.fighters[2].percent == 8 and not m.fighters[2].frozen,"two same-frame bolts freeze then shatter")
	check(b.runtime.hitstun_left > 0 and b.velocity.x > 0,"last shatter retains shared batch launch")
	check(m.status_telemetry(2).freeze_immunity == 1,"same-frame status ordered, not prechecked")
	a.free(); b.free()
	if not failures: print("PASS: ice match shatter (%d checks)" % checks)
	quit(1 if failures else 0)
