extends "res://tests/test_core_combat_lab.gd"
func run() -> void:
    var policy = load("res://scripts/core/presentation/presentation_state.gd").new()
    var pose: Dictionary = policy.sample({"locomotion": "idle", "strike_id": "1:1"}, 0)
    check(pose.clip == "Punch", "optional strike identity selects authored Punch")
    pose = policy.sample({"locomotion": "idle", "strike_id": "1:1"}, 3)
    check(is_equal_approx(pose.seconds, 0.05), "Punch uses unchanged 60Hz source time")
    pose = policy.sample({"locomotion": "idle", "strike_id": "1:2"}, 4)
    check(pose.seconds == 0.0, "new strike restarts same clip")
    pose = policy.sample({"status": "hitstun", "strike_id": "1:2"}, 5)
    check(pose.clip == "Hit", "hit outranks strike")
    policy.reset()
    check(policy.sample({"locomotion": "idle"}, 0).clip == "Idle", "absent optional strike preserves P3")
    var lab = load("res://scenes/combat_lab.tscn").instantiate()
    root.add_child(lab)
    lab.set_physics_process(false)
    for i in range(40): await tick(lab)
    key(KEY_F, true)
    await tick(lab)
    check(lab.imported_visuals[0].animation_player.has_animation("Punch"), "imported authored Punch exists")
    check(lab.imported_visuals[0].animation_player.assigned_animation == "Punch", "real lab presenter plays Punch")
    check(lab.imported_visuals[1].animation_player.assigned_animation == "Hit", "real victim presenter plays Hit")
    key(KEY_F, false)
    lab.free()
    if failures == 0: print("PASS: optional strike presentation and real lab animation")
    quit(1 if failures else 0)
