extends "res://tests/test_core_combat_lab.gd"
func run() -> void:
    var lab = load("res://scenes/combat_lab.tscn").instantiate()
    root.add_child(lab)
    lab.set_physics_process(false)
    lab.select_fighter(0,"turbofit")
    for i in range(40): await tick(lab)
    key(KEY_G,true)
    for i in range(12): await tick(lab)
    lab._process(0)
    check("power" in lab.telemetry_label.text and "anticipation" in lab.telemetry_label.text,"visible committed charge phase power telemetry")
    key(KEY_G,false)
    await tick(lab)
    var snapshot: Dictionary = lab.get_snapshot()
    check(snapshot.actors[0].cooldown_ticks == 42,"release reports actual 0.7 second cooldown, not Teknium deadline zero")
    snapshot.actors[0].kit.special.age = 900
    check(lab.simulation.kit_telemetry(1).special.age == 0,"diagnostic kit snapshot detached")
    lab.reset_lab()
    for i in range(40): await tick(lab)
    key(KEY_F,true)
    await tick(lab)
    key(KEY_F,false)
    check(lab.get_snapshot().actors[0].cooldown_ticks > 0,"active basic actual remaining clock")
    lab.simulation.cancel_action(1,"telemetry")
    check(lab.get_snapshot().actors[0].cooldown_ticks > 0,"interrupted basic retains truthful cooldown")
    lab.free()
    if not failures: print("PASS: Turbo HUD charge phase power actual cooldown and detached diagnostics")
    quit(1 if failures else 0)
