extends "res://tests/test_core_match_strikes.gd"
const Match = preload("res://scripts/core/match/match_simulation.gd")
func run() -> void:
	await eligibility()
	await interruptions()
	if failures == 0: print("PASS: core match eligibility (%d checks)" % checks)
	quit(1 if failures else 0)
func eligibility() -> void:
	var m = Match.new()
	var actors := []
	for id in [10, 20, 30, 40]:
		var actor = Actor.new()
		root.add_child(actor)
		actors.append(actor)
		m.register_actor(id, actor, 1 if id in [10, 20] else -1)
	m.reset({10: Vector3(0, 5, 0), 20: Vector3(1, 5, 0), 30: Vector3(1.5, 5, 0), 40: Vector3(2, 5, 0)})
	m.set_enabled(40, false)
	await tick(m, {10: frame(true)})
	check(m.fighters[10].percent == 0 and m.fighters[20].percent == 0, "self and assigned same team excluded")
	check(m.fighters[30].percent == 8 and m.fighters[40].percent == 0, "unassigned target eligible; disabled target excluded")
	check(m.events.size() == 1, "one instantaneous query, no self or team events")
	await tick(m)
	check(m.events.is_empty() and m.fighters[30].percent == 8, "no sustained hit volume after acceptance")
	m.reset({10: Vector3(-1, 5, 0), 20: Vector3(1, 5, 0), 30: Vector3(0, 5, 0), 40: Vector3(10, 5, 0)})
	await tick(m, {10: frame(true, 1), 20: frame(true, -1)})
	check(m.fighters[30].percent == 16, "actual two-source body contact sums incoming damage")
	check(actors[2].velocity.x > 0, "actual equal-strength launch uses smaller stable source ID")
	for actor in actors: actor.free()
func interruptions() -> void:
	var m = Match.new()
	var a = Actor.new()
	root.add_child(a)
	m.register_actor(10, a)
	m.reset({10: Vector3(0, 5, 0)})
	var f = frame(true)
	f.axis.y = -1
	await tick(m, {10: f})
	check(m.fighters[10].move_id == "UP AIR" and not m.fighters[10].activation_id.is_empty(), "source-backed vertical basic selects UP AIR, never SIDE/AIR STRIKE")
	m.reset({10: Vector3(0, 5, 0)})
	a.runtime.reset(true)
	a.runtime.step({"jump": true, "jump_held": true})
	a.apply_combat_launch(Vector3(5, 2, 0), 3)
	await tick(m, {10: frame(true)})
	check(a.runtime.states.status == "hitstun" and a.runtime.states.locomotion != "jump_startup", "hit interrupts startup and does not restore jump")
	check(not m.fighters[10].buffer.peek("attack").is_empty(), "hitstun request buffers rather than consuming")
	await tick(m)
	await tick(m)
	check(m.fighters[10].activation_id.is_empty(), "cannot activate on last locked movement tick")
	await tick(m)
	check(not m.fighters[10].activation_id.is_empty(), "buffer accepts first legal post-hitstun tick")
	m.reset({10: Vector3(0, 5, 0)})
	await tick(m)
	check(m.fighters[10].activation_id.is_empty(), "reset cannot leak buffered attack")
	await tick(m, {10: frame(true)})
	var f_jump = frame()
	f_jump.pressed.jump = true
	f_jump.held.jump = true
	await tick(m, {10: f_jump})
	check(a.velocity.y > 0, "generic strike cooldown allows legal air jump")
	for i in range(19): await tick(m)
	check(m.fighters[10].activation_id.is_empty() and m.fighters[10].move_id.is_empty(), "cooldown completion retires action identity without a new press")
	a.free()
