extends "res://tests/test_core_ice_match_shatter.gd"
func run():
	var m = Match.new(); var a = Actor.new(); var b = Actor.new()
	root.add_child(a); root.add_child(b)
	m.register_actor(1,a,-1,"ice_mage"); m.register_actor(2,b,-1,"turbofit")
	var rules = load("res://scripts/core/match/match_rules.gd").new()
	rules.respawn_protection_ticks = 3; rules.respawn_hitstun_ticks = 0
	m.configure_rules(rules); m.rematch()
	bolt(m,1,2,"freeze-stock"); await step(m)
	check(m.fighters[2].frozen,"stock fixture actual freeze")
	m._commit_kit_intents([{"kind":"spawn_projectile","projectile_kind":"frost_bolt","source":2,"activation_id":"owned","position":Vector3(0,5,0),"facing":1.0}])
	b.position.y = -9; await step(m)
	check(m.fighters[2].stocks == 2 and not m.fighters[2].frozen,"stock loss clears finite freeze")
	check(m.status_telemetry(2).freeze_immunity == 0,"stock clear does not grant thaw immunity")
	check(m.projectile_telemetry().is_empty(),"stock expires currently owned frost")
	bolt(m,1,2,"protected-stock"); await step(m)
	check(not m.fighters[2].frozen and m.fighters[2].percent == 0,"real respawn protection filters status")
	for i in 2: await step(m)
	bolt(m,1,2,"after-protection"); await step(m)
	check(m.fighters[2].frozen,"respawn exact expiry eligible")
	b.position.y = -9; await step(m)
	b.position.y = -9; await step(m)
	check(not m.result.is_empty() and m.result.winner_id == 1,"actual stock results")
	check(m.status_telemetry(2).freeze_remaining == 0 and m.status_telemetry(2).freeze_immunity == 0,"results clear status")
	check(m.projectile_telemetry().is_empty(),"results clear detached projectiles")
	m.rematch()
	check(m.result.is_empty() and m.status_telemetry(2).freeze_immunity == 0 and m.fighters[2].stocks == 3,"rematch clean status/resources")
	a.free(); b.free()
	if not failures: print("PASS: ice match stocks (%d checks)" % checks)
	quit(1 if failures else 0)
