extends "res://tests/test_core_defense_lab_motion.gd"
func run() -> void:
    var lab = load("res://scenes/combat_lab.tscn").instantiate()
    root.add_child(lab)
    lab.set_physics_process(false)
    lab.set_defense_enabled(true)
    await settle(lab)
    key(KEY_O, true); await tick(lab)
    lab.set_paused(true)
    var before: Dictionary = lab.simulation.defense_telemetry(2)
    var world: int = lab.simulation.tick
    for i in 3: await tick(lab)
    check(lab.simulation.tick == world and lab.simulation.defense_telemetry(2) == before, "pause cannot drain shield or age defense")
    lab.step_once(); await tick(lab)
    check(lab.simulation.tick == world + 1 and lab.simulation.defense_telemetry(2).shield_health == before.shield_health, "one step commits once while reset-held shield stays suppressed")
    lab._physics_process(1.0 / 60.0)
    check(lab.simulation.tick == world + 1, "no duplicate callback world tick")
    key(KEY_O, false)
    await settle(lab)
    key(KEY_D, true); key(KEY_E, true); await tick(lab)
    key(KEY_D, false); key(KEY_E, false)
    lab.set_paused(true)
    before = lab.simulation.defense_telemetry(1)
    for i in 3: await tick(lab)
    check(lab.simulation.defense_telemetry(1) == before, "paused dodge phase does not advance")
    lab.step_once(); await tick(lab)
    check(lab.simulation.defense_telemetry(1).remaining_ticks == before.remaining_ticks - 1, "step advances exactly one active defense clock")
    await settle(lab)
    lab.set_hitstop_enabled(true)
    key(KEY_LEFT, true); key(KEY_O, true); await tick(lab)
    key(KEY_LEFT, false); key(KEY_O, false)
    key(KEY_F, true); await tick(lab); key(KEY_F, false)
    check(lab.simulation.hitstop_telemetry(2).remaining_ticks == 4, "real unshielded contact creates hitstop")
    before = lab.simulation.defense_telemetry(2)
    check(before.cooldown_ticks == 20, "startup interruption leaves a nonzero defense clock to freeze")
    key(KEY_LEFT, true); key(KEY_O, true)
    for i in 4: await tick(lab)
    check(lab.simulation.defense_telemetry(2) == before, "defense clocks resources held throughout actual hitstop")
    check(not lab.simulation.fighters[2].buffer.debug_pending().is_empty(), "parsed shield press queues during hitstop")
    key(KEY_LEFT, false); key(KEY_O, false)
    lab.set_defense_enabled(true)
    check(lab.simulation.fighters[2].buffer.debug_pending().is_empty(), "policy toggle round boundary clears source queue")
    var source = lab.sources[0]
    var bindings: Dictionary = source.bindings.duplicate(true)
    lab.start_stock_match()
    for i in 40: await tick(lab)
    lab.actors[0].position.y = 7
    await tick(lab)
    key(KEY_E, true); await tick(lab)
    check(lab.simulation.defense_telemetry(1).air_charges == 0, "stock life spends air dodge")
    lab.actors[0].position.x = -17
    await tick(lab)
    check(lab.simulation.fighters[1].stocks == 2 and lab.simulation.defense_telemetry(1).air_charges == 1 and lab.simulation.defense_telemetry(1).shield_health == 100, "actual stock KO resets finite resources")
    for i in 45: await tick(lab)
    check(lab.simulation.defense_telemetry(1).state == "idle" and lab.simulation.fighters[1].buffer.debug_pending().is_empty(), "held shield suppressed across source-bound respawn")
    lab.reset_lab()
    for i in 40: await tick(lab)
    check(lab.simulation.defense_telemetry(1).state == "idle", "held shield suppressed across rematch")
    key(KEY_E, false); await tick(lab); key(KEY_E, true); await tick(lab)
    check(lab.simulation.defense_telemetry(1).state == "shield", "release and fresh press restores source shield")
    check(lab.sources[0] == source and source.bindings == bindings, "all lifecycle paths retain source and bindings")
    key(KEY_E, false)
    lab.free()
    if failures == 0: print("PASS: defense lab pause step real hitstop reset stocks and source suppression")
    quit(1 if failures else 0)
