extends "res://tests/test_core_combat_lab.gd"
func run() -> void:
    var lab = load("res://scenes/combat_lab.tscn").instantiate()
    root.add_child(lab)
    lab.set_physics_process(false)
    lab.select_fighter(0,"turbofit")
    lab.select_fighter(1,"turbofit")
    lab.set_ledges_enabled(true)
    for exit_key in [KEY_W,KEY_SPACE,KEY_S]:
        lab.reset_lab()
        for i in range(40): await tick(lab)
        key(KEY_A,true)
        key(KEY_RIGHT,true)
        for i in range(85): await tick(lab)
        key(KEY_A,false)
        key(KEY_RIGHT,false)
        key(KEY_D,true)
        key(KEY_LEFT,true)
        for i in range(19): await tick(lab)
        key(KEY_D,false)
        key(KEY_LEFT,false)
        check(lab.simulation.ledge_telemetry(1).anchor_id != "" and lab.simulation.ledge_telemetry(2).anchor_id != "","both physical Turbo ledge catches")
        key(exit_key,true)
        var other := KEY_UP if exit_key == KEY_W else KEY_ENTER if exit_key == KEY_SPACE else KEY_DOWN
        key(other,true)
        await tick(lab)
        key(exit_key,false)
        key(other,false)
        check(lab.simulation.ledge_telemetry(1).anchor_id == "" and lab.simulation.ledge_telemetry(2).anchor_id == "","Turbo both-sided physical ledge exit")
    lab.reset_lab()
    for i in range(40): await tick(lab)
    key(KEY_W,true)
    key(KEY_G,true)
    key(KEY_UP,true)
    key(KEY_L,true)
    await tick(lab)
    for code in [KEY_W,KEY_G,KEY_UP,KEY_L]: key(code,false)
    for slot in range(2):
        check(lab.actors[slot].velocity.y > 0 and lab.actors[slot].runtime.recovery_spent,"physical Rising Chord actual launch spent recovery")
        check(lab.imported_visuals[slot].output.clip == "Jump","committed source recovery fallback")
    for i in range(100): await tick(lab)
    check(not lab.actors[0].runtime.recovery_spent and not lab.actors[1].runtime.recovery_spent,"real terrain landing restores recovery resources")
    lab.free()
    if not failures: print("PASS: physical duplicate Turbo both ledges all exits recovery launch terrain resources")
    quit(1 if failures else 0)
