extends "res://tests/test_core_combat_lab.gd"
func settle(lab) -> void:
    lab.reset_lab()
    for i in range(40): await tick(lab)
    key(KEY_LEFT,true)
    await tick(lab)
    key(KEY_LEFT,false)
    for i in range(12): await tick(lab)
    lab.actors[0].position.x = -1
    lab.actors[1].position.x = 1
func run() -> void:
    var lab = load("res://scenes/combat_lab.tscn").instantiate()
    root.add_child(lab)
    lab.set_physics_process(false)
    lab.select_fighter(0,"turbofit")
    lab.set_hitstop_enabled(true)
    await settle(lab)
    key(KEY_F,true)
    for i in range(16): await tick(lab)
    key(KEY_K,true)
    await tick(lab)
    key(KEY_F,false)
    key(KEY_K,false)
    check(lab.simulation.fighters[1].percent == 8 and lab.simulation.fighters[2].percent == 14,"physical mixed kit trade commits both candidates")
    var visual = lab.imported_visuals[0]
    check(visual.output.clip == "HitReactRight", "actual Turbo incoming hit priority")
    var before: Dictionary = visual.output.duplicate(true)
    var local_tick: int = lab.simulation.kit_telemetry(1).simulation_tick
    for i in range(4):
        await tick(lab)
        check(visual.output == before and lab.simulation.kit_telemetry(1).simulation_tick == local_tick,"actual trade hitstop freezes committed Turbo pose")
    lab.set_defense_enabled(true)
    await settle(lab)
    key(KEY_E,true)
    await tick(lab)
    check(lab.imported_visuals[0].output.clip == "BlockIdle", "actual Turbo shield remains BlockIdle without an ability identity")
    key(KEY_E,false)
    await settle(lab)
    key(KEY_O,true)
    key(KEY_F,true)
    for i in range(20): await tick(lab)
    key(KEY_O,false)
    key(KEY_F,false)
    check(lab.simulation.fighters[2].percent == 0 and lab.simulation.defense_telemetry(2).shield_health < 100,"finite shield blocks real Turbo basic")
    lab.select_fighter(0,"teknium")
    lab.select_fighter(1,"turbofit")
    await settle(lab)
    lab.actors[0].position.x = 0
    lab.actors[1].position.x = 1.1
    key(KEY_L,true)
    key(KEY_G,true)
    for i in range(22): await tick(lab)
    key(KEY_L,false)
    key(KEY_G,false)
    check(lab.simulation.fighters[2].caught_by == 1,"physical Teknium grabs charging Turbo")
    check(lab.simulation.kit_telemetry(2).special.phase == "idle", "capture cancels Turbo episode")
    check(lab.imported_visuals[0].animation_player.assigned_animation == "GrabLoop" and lab.grab_visuals.size() == 1,"mixed caster retains source GrabLoop and live arcs")
    check(lab.imported_visuals[1].output.clip == "BlockIdle","caught Turbo explicitly labeled source fallback")
    lab.set_paused(true)
    lab.simulation.cancel_action(1,"paused release")
    lab._sync_visuals()
    check(lab.grab_visuals.is_empty() and lab.simulation.fighters[2].caught_by == 0,"paused mixed relation cleanup immediate")
    lab.set_paused(false)
    lab.start_stock_match()
    for i in range(40): await tick(lab)
    key(KEY_DOWN,true)
    key(KEY_L,true)
    await tick(lab)
    key(KEY_DOWN,false)
    key(KEY_L,false)
    check(lab.orb_visuals.size() == 1,"stock Turbo emits active Orb")
    lab.actors[1].position.y = -9
    await tick(lab)
    check(lab.orb_visuals.is_empty() and lab.simulation.fighters[2].stocks == 2,"real blast KO retires Orb and spends stock")
    lab.rematch_lab()
    check(lab.selected_fighters == ["teknium","turbofit"] and lab.simulation.fighters[2].stocks == 3,"rematch preserves selection resets stocks")
    lab.free()
    if not failures: print("PASS: physical mixed trades hitstop finite defense grabbed Turbo source arcs KO rematch")
    quit(1 if failures else 0)
